# Generated by Django 3.0.3 on 2020-03-05 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='city',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_id', models.CharField(max_length=4)),
                ('city_name', models.CharField(max_length=20)),
                ('country_id', models.CharField(max_length=4)),
            ],
        ),
    ]
