# Generated by Django 3.0.3 on 2020-03-19 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_airline'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('country_id', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('country_name', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'country',
                'managed': False,
            },
        ),
    ]
