# Generated by Django 3.0.3 on 2020-05-24 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_city'),
        ('api', '0003_country'),
    ]

    operations = [
    ]
