# Generated by Django 3.0.3 on 2020-05-24 06:24

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0004_merge_20200524_0617'),
    ]

    operations = [
        migrations.CreateModel(
            name='Terminal',
            fields=[
                ('terminal_id', models.IntegerField(primary_key=True, serialize=False)),
                ('terminal_name', models.CharField(blank=True, max_length=3, null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='city',
            options={'managed': False},
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('restaurant_id', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('restaurant_name', models.CharField(blank=True, max_length=20, null=True)),
                ('before_security', models.BooleanField(blank=True, null=True)),
                ('cusine_type', models.CharField(blank=True, max_length=20, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('terminal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Terminal')),
            ],
        ),
        migrations.CreateModel(
            name='RestaurantRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('star', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.CharField(blank=True, max_length=100, null=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Restaurant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'restaurant')},
                'index_together': {('user', 'restaurant')},
            },
        ),
    ]
